// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearExclusion():Promise<void>;

export function DoUpdate():Promise<main.UpdateInfo>;

export function ExportCSV(arg1:Array<main.Film>):Promise<string>;

export function Generate(arg1:string,arg2:boolean,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:boolean,arg7:Array<string>):Promise<main.GenerateResult>;

export function GetPlatforms():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function LoadExclusionCSV():Promise<main.ExclusionResult>;

export function LoadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
