// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearExclusion() {
  return window['go']['main']['App']['ClearExclusion']();
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function Generate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetPlatforms() {
  return window['go']['main']['App']['GetPlatforms']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadExclusionCSV() {
  return window['go']['main']['App']['LoadExclusionCSV']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
