// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function Generate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetPlatforms() {
  return window['go']['main']['App']['GetPlatforms']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
